[colors.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#6ae3fa"
green = "#3bd01d"
magenta = "#ff55ff"
red = "#f40e17"
white = "#ffffff"
yellow = "#edc809"

[colors.cursor]
cursor = "#f0cc09"
text = "#fefff2"

[colors.normal]
black = "#000000"
blue = "#1460d2"
cyan = "#00bbbb"
green = "#38de21"
magenta = "#ff005d"
red = "#ff0000"
white = "#bbbbbb"
yellow = "#ffe50a"

[colors.primary]
background = "#2E3440"
foreground = "#ffffff"

[colors.selection]
background = "#18354f"
text = "#b5b5b5"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8
